services:
  quizzo-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  quizzo-migration:
    build:
      context: ./backend
      dockerfile: Dockerfile.migration
    depends_on:
      - quizzo-mongo
    environment:
      - MONGO_HOST=quizzo-mongo
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=27017
      - MONGO_DB_NAME=quizzo

  quizzo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      quizzo-mongo:
        condition: service_started
      quizzo-migration:
        condition: service_completed_successfully
    environment:
      - MONGO_HOST=quizzo-mongo
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=27017
      - MONGO_DB_NAME=quizzo
      - SERVER_PORT=8089

  quizzo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
    depends_on:
      - quizzo-backend

volumes:
  mongodb_data:
